package pseudopad.ui;

import pseudopad.utils.ThemeManager;

/**
 *
 * @author Geger John Paul Gabayeron
 */
public class SplashScreenPanel extends javax.swing.JPanel {

    /**
     * Creates new form SplashScreenPanel
     */
    public SplashScreenPanel() {
        initComponents();
        
        if (ThemeManager.getInstance().isDarkMode()) {
            ImagePanel.setImageResourcePath("/img/PseudoPad_SplashScreenTitle_Dark.png");
        } else {
            ImagePanel.setImageResourcePath("/img/PseudoPad_SplashScreenTitle.png");
        }
    }
    
    public void setDebugText(String message) {
        SplashScreenText.setText(message);
    }
    
    public void setProgressValue(int progress) {
        SplashScreenProgressBar.setValue(Math.max(0, Math.min(100, progress)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagePanel = new pseudopad.ui.components.ImagePanel();
        jPanel2 = new javax.swing.JPanel();
        SplashScreenProgressBar = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        SplashScreenText = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(600, 375));
        setMinimumSize(new java.awt.Dimension(600, 375));
        setName("SplashScreenPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 375));
        setLayout(new java.awt.BorderLayout());

        ImagePanel.setAlignmentX(0.0F);
        ImagePanel.setAlignmentY(0.0F);
        ImagePanel.setImageResourcePath("");

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(ImagePanel, java.awt.BorderLayout.CENTER);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 75));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 75));
        jPanel2.setLayout(new java.awt.BorderLayout());

        SplashScreenProgressBar.setAlignmentX(0.0F);
        SplashScreenProgressBar.setAlignmentY(0.0F);
        jPanel2.add(SplashScreenProgressBar, java.awt.BorderLayout.PAGE_START);

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 64, 8);
        flowLayout1.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout1);

        SplashScreenText.setText("DEBUG TEXT");
        jPanel3.add(SplashScreenText);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pseudopad.ui.components.ImagePanel ImagePanel;
    private javax.swing.JProgressBar SplashScreenProgressBar;
    private javax.swing.JLabel SplashScreenText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
